org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

systemProp.net.minecraftforge.gradle.repo.recompile.fork=true
systemProp.net.minecraftforge.gradle.repo.recompile.fork.args=-Xmx4G

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

java_version=17
mod_loader=Forge

minecraft_version_range=[1.20.1,1.21)
forge_version_range=[47,)
loader_version_range=[47,)

l2hostility_version_range=[2.5.19,)

mod_group=io.github.torikun9971.l2hostilityxups
mod_id=l2hostilityxups
mod_name=L2 Hostility Xups
mod_filename=L2HostilityXups

mod_version=1.0.4
mod_license=MIT
mod_issue=https://github.com/Torikun9971/L2-Hostility-Xups/issues
mod_update_json=https://api.modrinth.com/updates/l2-hostility-xups/forge_updates.json
mod_homepage=https://github.com/Torikun9971/L2-Hostility-Xups
#mod_credits=
mod_authors=Torikun9971
mod_description=A mod that limits enemies with the Undying trait in L2 Hostility to revive only a certain number of times.

#mc_username=
#mc_uuid=