org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

java_version=21
mod_loader=NeoForge

minecraft_version_range=[1.21.1,1.22)
neoforge_version_range=[21.1.0,)
loader_version_range=[4,)

l2hostility_version_range=[3.0.12,)

mod_group=io.github.torikun9971.l2hostilityxups
mod_id=l2hostilityxups
mod_name=L2 Hostility Xups
mod_filename=L2HostilityXups

mod_version=1.0.2
mod_license=MIT
mod_issue=https://github.com/Torikun9971/L2-Hostility-Xups/issues
mod_update_json=https://api.modrinth.com/updates/l2-hostility-xups/forge_updates.json?neoforge=only
mod_homepage=https://github.com/Torikun9971/L2-Hostility-Xups
#mod_credits=
mod_authors=Torikun9971
mod_description=A mod that limits enemies with the Undying trait in L2 Hostility to revive only a certain number of times.

mc_username=
mc_uuid=

release_type=release
release_loaders=NeoForge
release_minecraft_versions=1.21.1

curseforge_id=1389149
curseforge_environments=Server,Client
curseforge_java_versions=21

modrinth_id=qfnIda6K